### ISSUE TITLE
Not super clear that "Sign-in with Slack" is a button

### ISSUE THREAD

**Issue by zachlatta** [maxwofford/excitedcornsilkpackages#24]
<img width="1552" alt="Screen Shot 2022-03-17 at 12 13 40 PM" src="https://user-images.githubusercontent.com/992248/158844696-eaee06f7-df11-4145-869c-9fa9350b3fe7.png">

Going through the flow for this, and it's not super clear to me from a UX perspective that the "Sign-in with Slack" text is a button.

Maybe if we put an outline around it, it would be more clear?

**Comment by geeky-sambhav** [comment]
I would like to contribute to this issue
